site_name: csrookie's website
theme:
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
  name: material
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/bearthesilly # <-- 请替换为您的 GitHub 用户名
    # - icon: fontawesome/solid/envelope
    #   link: xiongzhzh2023@shanghaitech.edu.cn # <-- 请替换为您的邮箱
use_directory_urls: false
plugins:
  - search
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
markdown_extensions:
  - mdx_math
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.pathconverter:
      absolute: false
nav:
  - Home: index.md
  - Course (Curriculum):
    - 高等数学上:
      - 写在最前面: 高等数学上/写在最前面/note.md
      - 第一&二章 函数 极限与连续: 
        - 第一章证明总结: 高等数学上/'证明'总结/note.md
        - 递推数列的极限: 高等数学上/递推数列的极限/note.md
        - 极限中的概念题: 高等数学上/极限中的概念题/note.md
        - 连续性 间断点 渐近线: 高等数学上/连续性 间断点 渐近线/note.md
        - 夹逼准则求极限: 高等数学上/夹逼准则求极限/note.md
        - 求函数极限: 高等数学上/求函数极限/note.md
        - 极限与连续随笔: 高等数学上/极限与连续随笔/note.md
      - 第三&四章 导数与微分 微分中值与导数应用: 
        - 导数定义与概念专题: 高等数学上/导数定义与概念专题/note.md
        - 第二&三&四章好题: 高等数学上/第二三四章好题/note.md
      - 第五章 积分: 
        - 不定积分与定积分概念: 高等数学上/不定积分与定积分概念/note.md
        - 不定积分专题: 高等数学上/不定积分专题/note.md
        - 定积分定义求极限: 高等数学上/定积分定义求极限/note.md
        - 反常积分敛散性: 高等数学上/反常积分敛散性/note.md
        - 积分不等式:  高等数学上/积分不等式/note.md
        - 积分及其应用: 高等数学上/积分及其应用/note.md
        - 积分的应用&函数形态: 高等数学上/积分的应用&函数形态/note.md
        - 积分递推公式: 高等数学上/积分递推公式/note.md
      - 手法&painpoint: 高等数学上/手法&painpoint/note.md
      - 第六章 微分方程:
        - 微分方程: 高等数学上/微分方程/note.md
      - 期末复习篇: 高等数学上/期末复习篇/note.md
      - 一元积分学好题: 高等数学上/一元积分学好题/note.md
    - 高等数学下: 
      - 第七章 向量空间与空间解析几何: 高等数学下/向量代数与空间总结/note.md
      - 第八章 多元函数的微分学:
        - 多元函数: 高等数学下/多元函数/note.md
        - 偏导数计算: 高等数学下/偏导数计算/note.md
        - 已知偏导反求函数: 高等数学下/已知偏导反求函数/note.md
        - 全微分的判定与计算: 高等数学下/全微分的判定与计算/note.md
        - 隐函数存在定理: 高等数学下/隐函数存在定理/note.md
        - 多元函数极值: 高等数学下/多元函数极值/note.md
      - 第九章 重积分: 
        - 二重积分: 高等数学下/二重积分/note.md
        - 二重积分中值定理: 高等数学下/二重积分中值定理/note.md
        - 二重积分好题: 高等数学下/二重积分好题/note.md
      - 期中总结: 高等数学下/期中总结/note.md
      - 高数好题上: 高等数学下/高数好题上/note.md
      - 第十章 曲线积分和曲面积分: 
        - 曲线与曲面积分: 高等数学下/曲线与曲面积分/note.md
        - 曲线与曲面积分总结: 高等数学下/曲线与曲面积分总结/note.md
        - 曲线与曲面积分荟萃: 高等数学下/曲线与曲面积分荟萃/note.md
      - 第十一章 级数:
        - 无穷级数和判别法: 高等数学下/无穷级数和判别法/note.md
        - 无穷级数选择题与反例: 高等数学下/无穷级数选择题与反例/note.md
        - 幂函数: 高等数学下/幂函数/note.md
        - 傅里叶级数: 高等数学下/傅里叶级数/note.md
      - 高数好题下: 高等数学下/高数好题下/note.md
    - 离散数学:
      - 写在最前面: 离散数学/写在最前面.md
      - 上半部分:
        - Lec1: 离散数学/上半部分/Lec1/note.md
        - Lec2&3: 离散数学/上半部分/Lec2&3/note.md
        - Lec4: 离散数学/上半部分/Lec4/note.md
        - Lec5: 离散数学/上半部分/Lec5/note.md
        - Lec6: 离散数学/上半部分/Lec6/note.md
        - Lec7: 离散数学/上半部分/Lec7/note.md
        - Lec8: 离散数学/上半部分/Lec8/note.md
        - Lec9: 离散数学/上半部分/Lec9/note.md
        - Lec10: 离散数学/上半部分/Lec10/note.md
        - Lec11: 离散数学/上半部分/Lec11/note.md
        - Lec12: 离散数学/上半部分/Lec12/note.md
        - Lec13&14: 离散数学/上半部分/Lec13&14/note.md
        - Lec15: 离散数学/上半部分/Lec15/note.md
        - 随笔&好题: 离散数学/上半部分/随笔&好题/note.md
      - 下半部分:
        - Lec1: 离散数学/下半部分/Lec1/note.md
        - Lec2: 离散数学/下半部分/Lec2/note.md
        - Lec3: 离散数学/下半部分/Lec3/note.md
        - Lec4: 离散数学/下半部分/Lec4/note.md
        - Lec5: 离散数学/下半部分/Lec5/note.md
        - Lec6: 离散数学/下半部分/Lec6/note.md
        - Lec7: 离散数学/下半部分/Lec7/note.md
        - Lec8: 离散数学/下半部分/Lec8/note.md
        - Lec9: 离散数学/下半部分/Lec9/note.md
        - Lec10: 离散数学/下半部分/Lec10/note.md
        - Lec11: 离散数学/下半部分/Lec11/note.md
        - Lec12: 离散数学/下半部分/Lec12/note.md
        - Lec13: 离散数学/下半部分/Lec13/note.md
        - Lec14: 离散数学/下半部分/Lec14/note.md
    - 线性代数:
      - 写在最前面: 线性代数/写在最前面.md
      - 课堂笔记: 线性代数/课堂笔记/note.md
      - 行列式与伴随矩阵: 线性代数/行列式与伴随矩阵/note.md
      - 手法与好题: 线性代数/手法与好题/note.md
      - 章节回顾: 线性代数/章节回顾/note.md
      - 总复习: 线性代数/总复习/note.md
    - 概率论:
      - 写在最前面: 概率论/写在最前面.md
      - Lec-handwriting:
        - Lec1-handwriting: 概率论/L1-handwriting.pdf
        - Lec2-handwriting: 概率论/L2-handwriting.pdf
        - Lec3-handwriting: 概率论/L3-handwriting.pdf
        - Lec4-handwriting: 概率论/L4-handwriting.pdf
        - Lec5-handwriting: 概率论/L5-handwriting.pdf
        - Lec6-handwriting: 概率论/L6-handwriting.pdf
        - Lec7-handwriting: 概率论/L7-handwriting.pdf
        - Lec8-handwriting: 概率论/L8-handwriting.pdf
        - Lec9-handwriting: 概率论/L9-handwriting.pdf
        - Lec10-handwriting: 概率论/L10-handwriting.pdf
      - Note:
        - Lec1: 概率论/SI140-note/Lec1.pdf
        - Lec2-3: 概率论/SI140-note/Lec2-3.pdf
        - Lec4-5-6: 概率论/SI140-note/Lec4-5-6.pdf
        - Lec7-8: 概率论/SI140-note/Lec7-8.pdf
        - Lec9-10-11: 概率论/SI140-note/Lec9-10-11.pdf
        - 期中部分总结: 概率论/SI140-note/期中部分总结.pdf
        - Chapter4: 概率论/SI140-note/Chapter4.pdf
        - Chapter5: 概率论/SI140-note/Chapter5.pdf
        - Chapter6: 概率论/SI140-note/Chapter6.pdf
        - Chapter7-8: 概率论/SI140-note/Chapter7-8.pdf
        - Chapter9: 概率论/SI140-note/Chapter9.pdf
        - Chapter10: 概率论/SI140-note/Chapter10.pdf
        - 期末总复习: 概率论/SI140-note/期末总复习.pdf
        - Skill: 概率论/SI140-note/Skill.pdf
    - C&C++ (CS100):
      - 写在最前面: CS100(C&C++)/写在最前面.md
      - 课件:
        - L0: CS100(C&C++)/slides/l0/l0.md
        - L1: CS100(C&C++)/slides/l1/l1.md
        - L2: CS100(C&C++)/slides/l2/l2.md
        - L3: CS100(C&C++)/slides/l3/l3.md
        - L4: CS100(C&C++)/slides/l4/l4.md
        - L5: CS100(C&C++)/slides/l5/l5.md
        - L6: CS100(C&C++)/slides/l6/l6.md
        - L7: CS100(C&C++)/slides/l7/l7.md
        - L8: CS100(C&C++)/slides/l8/l8.md
        - L9: CS100(C&C++)/slides/l9/l9.md
        - L10: CS100(C&C++)/slides/l10/l10.md
        - L11: CS100(C&C++)/slides/l11/l11.md
        - L12: CS100(C&C++)/slides/l12/l12.md
        - L13: CS100(C&C++)/slides/l13/l13.md
        - L14: CS100(C&C++)/slides/l14/l14.md
        - L15: CS100(C&C++)/slides/l15/l15.md
        - L16: CS100(C&C++)/slides/l16/l16.md
        - L17: CS100(C&C++)/slides/l17/l17.md
        - L18: CS100(C&C++)/slides/l18/l18.md
        - L19: CS100(C&C++)/slides/l19/l19.md
        - L20: CS100(C&C++)/slides/l20/l20.md
        - L21: CS100(C&C++)/slides/l21/l21.md
        - L22: CS100(C&C++)/slides/l22/l22.md
        - L23: CS100(C&C++)/slides/l23/l23.md
        - L24: CS100(C&C++)/slides/l24/l24.pdf
        - L25: CS100(C&C++)/slides/l25/l25.md
        - L26: CS100(C&C++)/slides/l26/l26.md
        - L27: CS100(C&C++)/slides/l27/l27.md
        - L28: CS100(C&C++)/slides/l28/l28.md
      - C++自学note: CS100(C&C++)/C++自学笔记.md
      - core: CS100(C&C++)/core.md
      - 课堂note: CS100(C&C++)/课堂.md
    - Data Structure and Algorithm (CS101):
      - 基本结构与算法分析: Data_Structure_and_Algorithm/基本结构与算法分析.md
      - 搜索与排序: Data_Structure_and_Algorithm/搜索与排序.md
      - 算法: Data_Structure_and_Algorithm/算法.md
      - 进阶与拓展: Data_Structure_and_Algorithm/进阶与拓展misc.md
    - 信号与系统:
      - 写在最前面: 信号与系统/写在最前面.md
      - slides: 
        - Chapter1: 信号与系统/Chapter 1.pdf
        - Chapter2: 信号与系统/Chapter 2.pdf
        - Chapter3: 信号与系统/Chapter 3.pdf
        - Chapter4: 信号与系统/Chapter 4.pdf
        - Chapter5: 信号与系统/Chapter 5.pdf
        - Chapter6: 信号与系统/Chapter 6.pdf
        - Chapter7: 信号与系统/Chapter 7.pdf
        - Chapter9: 信号与系统/Chapter 9.pdf
        - Chapter10: 信号与系统/Chapter 10.pdf
      - Note:
        - Chapter1LecNote: 信号与系统/Note/Chapter1LecNote.pdf
        - Chapter2LecNote: 信号与系统/Note/Chapter2LecNote.pdf
        - Chapter3LecNote: 信号与系统/Note/Chapter3LecNote.pdf
        - Chapter3Review: 信号与系统/Note/Chapter3Review.pdf
        - Chapter4Review: 信号与系统/Note/Chapter4Review.pdf
        - Chapter5Review: 信号与系统/Note/Chapter5Review.pdf
        - Chapter6Review: 信号与系统/Note/Chapter6Review.pdf
        - Chapter8Review: 信号与系统/Note/Chapter8Review.pdf
        - Chapter9Review: 信号与系统/Note/Chapter9Review.pdf
        - Chapter10Review: 信号与系统/Note/Chapter10Review.pdf
        - 期中cheatsheet: 信号与系统/Note/期中cheatsheet.pdf
        - 期末cheatsheet: 信号与系统/Note/期末cheatsheet.pdf

    - Artificial Intelligence (CS181):
      - 写在最前面: 人工智能/写在最前面.md
      - Search: 人工智能/Search.md
      - CSP: 人工智能/CSP.md
      - Adversial_Search: 人工智能/Adversial_Search.md
      - Propositional_Logic: 人工智能/Propositional_Logic.md
      - First_Order_Logic: 人工智能/First_Order_Logic.md
      - Bayes_Net:
        - BN1: 人工智能/BN1.md
        - BN2: 人工智能/BN2.md
      - Markov Decision Process: 人工智能/Markov_Decision.md
      - Reinforcement Learning: 人工智能/Reinforcement_learning.md
      - Supervised Learning: 人工智能/Supervised_Learning.md
      - Final_Review (Second Half): 人工智能/181_review.pdf
      - cheatsheet_mid: 人工智能/cheatsheet_mid.pdf
      - cheatsheet_final: 人工智能/cheatsheet_final.pdf
    - Introduction to Machine Learning (CS182):
      - 写在最前面: 机器学习/写在最前面.md
      - 传统机器学习部分:
        - Decision_Tree: 机器学习/传统机器学习部分/Decision_Tree.pdf
        - KNN: 机器学习/传统机器学习部分/KNN.pdf
        - Perceptron: 机器学习/传统机器学习部分/Perceptron.pdf
        - SVM: 机器学习/传统机器学习部分/SVM.pdf
        - Regression: 机器学习/传统机器学习部分/Regression.pdf
        - Logistics_Regression: 机器学习/传统机器学习部分/Logistics_Regression.pdf
        - MLE_MAP: 机器学习/传统机器学习部分/MLE_MAP.pdf
        - Boosting_Factorization: 机器学习/传统机器学习部分/Boosting_Factorization.pdf
        - Bagging_Random_Forest: 机器学习/传统机器学习部分/Bagging_Random_Forest.pdf
        - Kmean: 机器学习/传统机器学习部分/Kmean.pdf
        - GMM_EM: 机器学习/传统机器学习部分/GMM_EM.pdf
        - Note_All: 机器学习/传统机器学习部分/iml_note_all.pdf
      - 神经网络:
        - feature_engineering: 机器学习/神经网络部分/feature_engineering.md
        - CNN: 机器学习/神经网络部分/CNN.md
        - practical_aspects: 机器学习/神经网络部分/practical_aspects.md
        - RNN: 机器学习/神经网络部分/RNN.md
        - Transformer: 机器学习/神经网络部分/Transformer.md
      - Math_Foundation: 机器学习/math_foundation.pdf
      - Review (First Half): 机器学习/iml_review(first_half).pdf
      - IML_cheatsheet: 机器学习/iml_chsh.pdf
    - Computer Architecture (CS110):
      - 写在最前面: CA/写在最前面.md
      - Info-Representation: CA/Info-Representation.md
      - Idea_Representation_note: CA/Idea_Representation_note.pdf
      - C_Language: CA/C_Language.md
      - C_note: CA/C_note.pdf
      - RISC-V: CA/RISC-V.md
      - RISC-V_note: CA/RISC-V_note.pdf
      - CALL: CA/CALL.md
      - CALL_note: CA/CALL_note.pdf
      - Digital_Cirtuit: CA/Digital_Circuit.md
      - Digital_Circuit_note: CA/Digital_Circuit_note.pdf
      - Datapath_Controller: CA/Datapath_Controller.md
      - Datapath_note: CA/Datapath_note.pdf
      - Pipeline_note: CA/Pipeline_note.pdf
      - Paralellism_note(1): CA/Paralellism_note.pdf
      - Parallelism(2): CA/Parallelism(2).md
      - TLP: CA/TLP.md
      - Hardware_Multithreading: CA/Hardware_Multithreading.md
      - Advanced_Cache: CA/Advanced_Cache.md
      - OS_IO: CA/OS_IO.md
      - Virtual_Memory: CA/Virtual_Memory.md
      - Note_All: CA/ca_note_all.pdf
      - Cheatsheet: CA/ca_chsh.pdf
    - Intro to Computer Vision and Computational Photography (UCB CS180):
      - Project:
        - Intro: UCB_CS180/project/intro.html
        - Proj 0: UCB_CS180/project/proj0/proj0.md
        - Proj 1: UCB_CS180/project/proj1/proj1.md
        - Proj 2: UCB_CS180/project/proj2/proj2.md
        - Proj 3: UCB_CS180/project/proj3/proj3.md
        - Proj 4: UCB_CS180/project/proj4/proj4.md
      - Midterm_Review: UCB_CS180/midterm_review.pdf
    - Natural Languange Processing (UCB EECS183):
      - Midterm_Review: UCB_EECS183/mid-review.pdf
      - Midterm_Cheatsheet: UCB_EECS183/cheatsheet_mid.pdf
  - Course (General Education):
    - 普通物理:
      - 写在最前面: 普通物理/写在最前面.md
      - slides: 
        - Lec2: 普通物理/Lect2_Kinematics 质点运动学.pdf
        - Lec3: 普通物理/Lect3_Dynamics 质点动力学-1.pdf
        - Lec4: 普通物理/Lect4_Dynamics 质点动力学-2.pdf
        - Lec5: 普通物理/Lect5_Work_energy 功和能.pdf
        - Lec6: 普通物理/Lect6_Potential Energy_势能.pdf
        - Lec7: 普通物理/Lect7_Momentum_动量-预习.pdf
        - Lec8: 普通物理/Lect8_Collision and elasticity 碰撞和弹性.pdf
        - Lec9: 普通物理/Lect9 刚体.pdf
        - Lec10: 普通物理/Lect10 力矩、角动量.pdf
        - Lec11: 普通物理/Lect11 平衡、流体力学.pdf
        - Lec12: 普通物理/Lect12 万有引力.pdf
        - Lec13: 普通物理/Lect13_Oscillation 振动.pdf
        - Lec14: 普通物理/Lect14_MechanicalWave-2024.pdf
        - Lec15: 普通物理/Lect15-Mechanical Wave-2-2024更新版.pdf
        - Lec16: 普通物理/Lect16_Sound and Hearing-2024(1).pdf
        - Lec17: 普通物理/Lect17_Temperature+and+Heat 2024(1).pdf
        - Lec18: 普通物理/Lect18_Thermal+Properties_2024.pdf
        - Lec19: 普通物理/Lect19_First+Thermodynamics+Law_2024-更正版2.pdf
        - 热学复习: 普通物理/热学复习.pdf
        - 振动和波动复习: 普通物理/振动和波动复习.pdf
      - Review:
        - 期中总结: 普通物理/期中总结.pdf
        - 期末总结: 普通物理/期末总结.pdf
    - 生命科学导论:
      - 写在最前面: 生命科学导论/写在最前面.md
      - slides:
        - Lec1: 生命科学导论/lecture1.pdf
        - Lec2: 生命科学导论/lecture2.pdf
        - Lec3: 生命科学导论/lecture3.pdf
        - Lec4: 生命科学导论/lecture4.pdf
        - Lec5: 生命科学导论/lecture5.pdf
        - Lec6: 生命科学导论/lecture6.pdf
        - Lec7: 生命科学导论/lecture7.pdf
        - Lec8: 生命科学导论/lecture8.pdf
        - Lec9: 生命科学导论/lecture9.pdf
        - Lec10: 生命科学导论/lecture10.pdf
        - Lec11: 生命科学导论/lecture11.pdf
        - Lec12: 生命科学导论/lecture12.pdf
        - Lec13: 生命科学导论/lecture13.pdf
        - Lec14: 生命科学导论/lecture14.pdf
        - Lec15: 生命科学导论/lecture15.pdf
      - Final_Review: 生命科学导论/final_review.pdf
  - Course (Extracurriculum):
    - Deep Learning:
      - 'Partition One: Fundamental + Convolution' : deeplearning_note/深度学习自学.md
      - 'Partition Two: Sequence Model' : sequence model/sequence_model.md
      - 'Transformer' : transformer_note/transformer_note.md
    - GAMES101: 
      - Note: GAMES101/note.md
      - Homework: GAMES101/note_hw.md
    - 动手学深度学习:
      - 预备知识:
        - 数据操作与数据预处理 : 动手学深度学习/预备知识/数据操作与数据预处理.md
        - 矩阵计算与自动求导 : 动手学深度学习/预备知识/矩阵计算与自动求导.md
      - 线性神经网络:
        - 线性回归 : 动手学深度学习/线性神经网络/线性回归.md
        - softmax : 动手学深度学习/线性神经网络/softmax.md
      - 多层感知机:
        - 感知机: 动手学深度学习/多层感知机/感知机.md
        - 模型选择&欠/过拟合: 动手学深度学习/多层感知机/模型选择_欠拟合_过拟合.md
        - 权重衰退: 动手学深度学习/多层感知机/权重衰退.md
      - 注意力机制:
        - 注意力: 动手学深度学习/注意力机制/注意力.md
        - 多头注意力: 动手学深度学习/注意力机制/多头注意力.md
        - 自注意力与位置编码: 动手学深度学习/注意力机制/自注意力与位置编码.md
        - Transformer: 动手学深度学习/注意力机制/Transformer.md
    - Reinforcement Learning (CS285, Berkeley):
      - Supervised_Learning_of_Behaviors: RL_CS285/Supervised_Learning_of_Behaviors.md
      - Introduction_to_Reinforcement_Learning: RL_CS285/Introduction_to_Reinforcement_Learning.md
      - Policy_Gradient: RL_CS285/Policy_Gradient.md
      - Actor-Critic: RL_CS285/Actor_Critic.md
      - Model_Based_RL: RL_CS285/Model_Based_RL.md
  - Blog: 
    - Datawhale: machine_learning/Datawhale/note.md
    - PointNet: Blog/PointNet/analysis.md
    - PointMAE: Blog/PointMAE/analysis.md
    - NeRF&Instant_NGP: Blog/NeRF&Instant_NGP/note.md
    - 3DGS: Blog/3DGS/note.md
    - 3DGS_reproduction: Blog/3DGS_reproduction/note.md
    - Intern_Blog: Blog/AAAI2025/log.md
  - CV: Zhangzhi_Xiong_CV.pdf

copyright: Copyright &copy; 2025 csrookie